//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WinFormsLander.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WinFormsLander.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap Area1_Neiborhood_Typed {
            get {
                object obj = ResourceManager.GetObject("Area1_Neiborhood_Typed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Area2_JupiterMoons_Typed {
            get {
                object obj = ResourceManager.GetObject("Area2_JupiterMoons_Typed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Area3_OtherMoons_Typed {
            get {
                object obj = ResourceManager.GetObject("Area3_OtherMoons_Typed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Area4_DwarfPlanets_Typed {
            get {
                object obj = ResourceManager.GetObject("Area4_DwarfPlanets_Typed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Area5_AsteroidsTyped {
            get {
                object obj = ResourceManager.GetObject("Area5_AsteroidsTyped", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Area6_MetroidUniverse_Typed {
            get {
                object obj = ResourceManager.GetObject("Area6_MetroidUniverse_Typed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Asteroid {
            get {
                object obj = ResourceManager.GetObject("Asteroid", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap AuxRocketBoost {
            get {
                object obj = ResourceManager.GetObject("AuxRocketBoost", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ball1 {
            get {
                object obj = ResourceManager.GetObject("ball1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap blackSquare {
            get {
                object obj = ResourceManager.GetObject("blackSquare", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Blue_Ore {
            get {
                object obj = ResourceManager.GetObject("Blue_Ore", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap explosion {
            get {
                object obj = ResourceManager.GetObject("explosion", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Green_Ore {
            get {
                object obj = ResourceManager.GetObject("Green_Ore", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap LanderType01 {
            get {
                object obj = ResourceManager.GetObject("LanderType01", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap LanderType01Crash {
            get {
                object obj = ResourceManager.GetObject("LanderType01Crash", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap LanderType02 {
            get {
                object obj = ResourceManager.GetObject("LanderType02", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap LanderType02Crash {
            get {
                object obj = ResourceManager.GetObject("LanderType02Crash", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap LanderType03 {
            get {
                object obj = ResourceManager.GetObject("LanderType03", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap LanderType03Crash {
            get {
                object obj = ResourceManager.GetObject("LanderType03Crash", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap LanderType04 {
            get {
                object obj = ResourceManager.GetObject("LanderType04", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap LanderType04Crash {
            get {
                object obj = ResourceManager.GetObject("LanderType04Crash", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap LanderType05 {
            get {
                object obj = ResourceManager.GetObject("LanderType05", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap LanderType05_Left {
            get {
                object obj = ResourceManager.GetObject("LanderType05_Left", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap LanderType05_Right {
            get {
                object obj = ResourceManager.GetObject("LanderType05_Right", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap LanderType05Crash {
            get {
                object obj = ResourceManager.GetObject("LanderType05Crash", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap LanderType06 {
            get {
                object obj = ResourceManager.GetObject("LanderType06", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap LanderType06Crash {
            get {
                object obj = ResourceManager.GetObject("LanderType06Crash", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap LanderType07 {
            get {
                object obj = ResourceManager.GetObject("LanderType07", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap LanderType07Crash {
            get {
                object obj = ResourceManager.GetObject("LanderType07Crash", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap LanderType08 {
            get {
                object obj = ResourceManager.GetObject("LanderType08", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap LanderType08Crash {
            get {
                object obj = ResourceManager.GetObject("LanderType08Crash", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap LanderType09 {
            get {
                object obj = ResourceManager.GetObject("LanderType09", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap LanderType09Crash {
            get {
                object obj = ResourceManager.GetObject("LanderType09Crash", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap LanderTypeX1 {
            get {
                object obj = ResourceManager.GetObject("LanderTypeX1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap LanderTypeX1Crash {
            get {
                object obj = ResourceManager.GetObject("LanderTypeX1Crash", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Landscape_Mars {
            get {
                object obj = ResourceManager.GetObject("Landscape_Mars", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Landscape_Moon {
            get {
                object obj = ResourceManager.GetObject("Landscape_Moon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap LED_OFF {
            get {
                object obj = ResourceManager.GetObject("LED_OFF", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap LED_ON {
            get {
                object obj = ResourceManager.GetObject("LED_ON", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap LeftBoost {
            get {
                object obj = ResourceManager.GetObject("LeftBoost", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Location_Aether {
            get {
                object obj = ResourceManager.GetObject("Location_Aether", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Location_Amalthea {
            get {
                object obj = ResourceManager.GetObject("Location_Amalthea", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Location_BiologicSpaceLab {
            get {
                object obj = ResourceManager.GetObject("Location_BiologicSpaceLab", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Location_Callisto {
            get {
                object obj = ResourceManager.GetObject("Location_Callisto", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Location_Ceres {
            get {
                object obj = ResourceManager.GetObject("Location_Ceres", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Location_DarkAether {
            get {
                object obj = ResourceManager.GetObject("Location_DarkAether", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Location_Earth {
            get {
                object obj = ResourceManager.GetObject("Location_Earth", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Location_Eris {
            get {
                object obj = ResourceManager.GetObject("Location_Eris", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Location_Europa {
            get {
                object obj = ResourceManager.GetObject("Location_Europa", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Location_Ganymede {
            get {
                object obj = ResourceManager.GetObject("Location_Ganymede", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Location_Haumea {
            get {
                object obj = ResourceManager.GetObject("Location_Haumea", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Location_Hygiea {
            get {
                object obj = ResourceManager.GetObject("Location_Hygiea", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Location_Iapetus {
            get {
                object obj = ResourceManager.GetObject("Location_Iapetus", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Location_Ida {
            get {
                object obj = ResourceManager.GetObject("Location_Ida", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Location_Io {
            get {
                object obj = ResourceManager.GetObject("Location_Io", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Location_Mars {
            get {
                object obj = ResourceManager.GetObject("Location_Mars", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Location_Mercury {
            get {
                object obj = ResourceManager.GetObject("Location_Mercury", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Location_Miranda {
            get {
                object obj = ResourceManager.GetObject("Location_Miranda", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Location_Moon {
            get {
                object obj = ResourceManager.GetObject("Location_Moon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Location_Pallas {
            get {
                object obj = ResourceManager.GetObject("Location_Pallas", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Location_Pluto {
            get {
                object obj = ResourceManager.GetObject("Location_Pluto", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Location_Sedna {
            get {
                object obj = ResourceManager.GetObject("Location_Sedna", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Location_SR388 {
            get {
                object obj = ResourceManager.GetObject("Location_SR388", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Location_TallonIV {
            get {
                object obj = ResourceManager.GetObject("Location_TallonIV", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Location_Titan {
            get {
                object obj = ResourceManager.GetObject("Location_Titan", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Location_Titania {
            get {
                object obj = ResourceManager.GetObject("Location_Titania", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Location_Triton {
            get {
                object obj = ResourceManager.GetObject("Location_Triton", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Location_Varuna {
            get {
                object obj = ResourceManager.GetObject("Location_Varuna", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Location_Venus {
            get {
                object obj = ResourceManager.GetObject("Location_Venus", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Location_Vesta {
            get {
                object obj = ResourceManager.GetObject("Location_Vesta", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Location_Zebes {
            get {
                object obj = ResourceManager.GetObject("Location_Zebes", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Locked {
            get {
                object obj = ResourceManager.GetObject("Locked", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap LunarLander {
            get {
                object obj = ResourceManager.GetObject("LunarLander", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap LZ {
            get {
                object obj = ResourceManager.GetObject("LZ", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Metroid {
            get {
                object obj = ResourceManager.GetObject("Metroid", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Off_Map_Cursor {
            get {
                object obj = ResourceManager.GetObject("Off_Map_Cursor", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap OreCollected {
            get {
                object obj = ResourceManager.GetObject("OreCollected", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Parachute {
            get {
                object obj = ResourceManager.GetObject("Parachute", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Red_Ore {
            get {
                object obj = ResourceManager.GetObject("Red_Ore", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap RightBoost {
            get {
                object obj = ResourceManager.GetObject("RightBoost", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap RocketBoost {
            get {
                object obj = ResourceManager.GetObject("RocketBoost", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap UpBoost {
            get {
                object obj = ResourceManager.GetObject("UpBoost", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
